quiz_app/quiz/forms.py
from flask_wtf import FlaskForm
from wtforms import RadioField, SubmitField


# FORMS for quiz creation. PLACEHOLDER FOR NOW, MVP is student UI
class GenerateQuizForm(FlaskForm):
    submit = SubmitField('Submit')

quiz_app/main/routes.py
from flask import render_template, request, Blueprint
from quiz_app.questions.question_types.question_generator import generate_two_number_addition_or_subtraction_question
from flask_babel import gettext

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/index')
@main.route('/home')
def index():
    return render_template('home.html')


@main.route("/about")
def about():
    print(gettext('Hello World'))
    return render_template('about.html', title=gettext('About'))

quiz_app/questions/routes.py
from flask import render_template, Blueprint
from quiz_app.questions.question_types.question_generator import generate_two_number_addition_or_subtraction_question
import random

questions = Blueprint('questions', __name__)


@questions.route('/addition')
def addition_quiz():
    question_data = generate_two_number_addition_or_subtraction_question('addition')
    return render_template('question.html', question=question_data['question_string'],
                           answers=question_data['all_answers'])


@questions.route('/subtraction')
def subtraction_quiz():
    question_data = generate_two_number_addition_or_subtraction_question('subtraction')
    return render_template('question.html', question=question_data['question_string'],
                           answers=question_data['all_answers'])

quiz_app/quiz/routes.py
import json
import uuid
import io
import qrcode
import base64
from flask import render_template, request, Blueprint, redirect, url_for, session

from quiz_app.quiz.forms import GenerateQuizForm
from quiz_app.models import Question, Quiz
from quiz_app import db
from quiz_app.questions.question_types.utils.registry import QuestionRegistry
quiz = Blueprint('quiz', __name__)


@quiz.route('/')
@quiz.route('/index')
@quiz.route('/home')
def home():
    return render_template('home.html', title='Welcome')


@quiz.route('/create_quiz', methods=['GET', 'POST'])
def create_quiz():
    topic = False
    form = GenerateQuizForm()

    if form.validate_on_submit():
        # teacher submits form
        # create quiz (mock it for now)
        # insert all quiz components into database
        question_registry = QuestionRegistry()
        questions = question_registry.generate_questions(10, seed=0)
        correct_answer_indices = [question['correct_answer_index'] for question in questions]
        json_questions = [json.dumps(question) for question in questions]

        # Add to db
        # Add quiz
        quiz_uid = str(uuid.uuid4())
        quiz = Quiz(quiz_uid=quiz_uid)
        db.session.add(quiz)
        quiz_id = db.session.query(Quiz).filter_by(quiz_uid=quiz_uid).one().quiz_id
        session['quiz_id'] = quiz_id
        i = 0
        for correct_answer_index, question_json in zip(correct_answer_indices, json_questions):
            question = Question(quiz_id=quiz_id,
                                question_json=question_json,
                                correct_answer_index=correct_answer_index,
                                question_number=i)
            db.session.add(question)
            i += 1
        db.session.commit()
        return redirect(url_for('quiz.quiz_lobby'))

    return render_template('create_quiz.html', form=form, topic=topic)


@quiz.route('/quiz_lobby', methods=['GET', 'POST'])
def quiz_lobby():

    qrcode_img = qrcode.make(url_for('student.student_landing', quiz_id=session['quiz_id'], _external=True))
    qrcode_png = io.BytesIO()
    qrcode_img.save(qrcode_png, 'png')
    qrcode_png_str = "data:image/png;base64,"
    qrcode_png_str += base64.b64encode(qrcode_png.getvalue()).decode('utf8')
    return render_template('teacher_quiz_lobby.html', quiz_id=session['quiz_id'], qrcode_png_str=qrcode_png_str)

quiz_app/templates/about.html
{%  extends "base.html" %}

{% block content %}
    <h1>test</h1>
{% endblock %}

quiz_app/templates/base.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
         <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
        <title>{{ title }}</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('main.index') }}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('student.student_landing') }}">Student</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('quiz.create_quiz') }}">Teacher</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        {%  block content %}{% endblock %}
        {%  block scripts %}{% endblock %}
         <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    <script id="MathJax-script" async
      src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js">
    </script>
</body>
</html>

    </body>
</html>

quiz_app/templates/create_quiz.html
{% extends "base.html" %}
{% block content %}
    <br/>
    <img alt="Quizzly logo" class="center" src="{{ url_for('static', filename='images/quizzly logo.png')}}" width="80">
    <h2 style="margin: 2px" align="center">Please select a Quiz option below</h2>
    <br/>
    <div class="container" align="center">
    <form method="POST">
        {{ form.hidden_tag() }}
        {{ form.submit() }}
    </form>
    </div>

    </div>
{% endblock %}

quiz_app/templates/home.html
{% extends "base.html" %}
{% block content %}
    <br/>
    <h6 align="center" class="site-header"> Welcome to </h6>
    <h1 align="center" class="site-header"> Quizzly </h1>
    <br>
    <img alt="Quizzly logo" class="center" src="{{ url_for('static', filename='images/quizzly logo.png')}}" width="110">
    <br>
    <h4 align="center" class="site-header">Choose your user type</h4>
    <div class="btn-group-vertical" style="display: flex; align-items: center">
        <nav>
            <a href="{{ url_for('student.student_landing')}}">
                <button class="home-button-custom">{% trans %}Student{% endtrans %}</button>
            </a>
        </nav>
        <nav>
            <a href="{{ url_for('quiz.create_quiz')}}">
                <button class="home-button-custom">Teacher</button>
            </a>
        </nav>
    </div>
{% endblock %}

quiz_app/templates/question.html
{%  extends "base.html" %}

{% block content%}
    <br/>
{#    need to replace with dynamic question numbering#}
    <div class="circle" align="center" style="margin-bottom: 10px">
        <h6 style="margin-top: 20px; font-size: 20px">{{question_index+1}}/{{n_questions}}</h6>
    </div>
    <h5 align="center">Please complete the quiz by choosing one of the following multiple choice answers for each question</h5>
    <br>
    <h2 align="center">{{question}}</h2>
    <br/>
    {% if figure_png is defined %}
        <div class="container", align="center">
        <img src="{{ figure_png }}"/>
        </div>
    {% endif %}
    <br/>
    <div class="btn-group-vertical" style="display: flex; align-items: center">
        {% for answer in answers %}
            <form method="POST">
            <input type="hidden", name="answer_index" value="{{ loop.index0 }}">
            <input type="hidden", name="question_id" value="{{ question_id }}">
            <button class="quiz-button-custom">{{answer}}</button>
            </form>
        {% endfor %}
    </div>
{% endblock %}

quiz_app/templates/quiz.html
{% extends "base.html" %}
{% block content%}
    <img class="center" style="margin-bottom: 10px" src="{{ url_for('static', filename='images/quizzly logo.png')}}" width="75">
    <h5 align="center">Please complete the quiz by choosing one of the following multiple choice answers for each question</h5>
    <br>
    <h2 align="center">{{question}}</h2>
    <br/>
    <div class="btn-group-vertical" style="display: flex; align-items: center">
        {% for answer in answers %}
            <button class="quiz-button-custom">{{answer}}</button>
        {% endfor %}
    </div>
{% endblock %}

quiz_app/templates/quiz_creation.html
{% extends "base.html" %}
{% block content %}
    <br/>
    <h2 style="margin: 2px" align="center">Configure your Quiz</h2>
    <br/>

{% endblock %}

quiz_app/templates/quiz_results.html
{% extends "base.html" %}
{% block content %}
    <br/>
    <img alt="Quizzly logo" class="center" src="{{ url_for('static', filename='images/quizzly logo.png')}}" width="60">
    <br/>
{#    # needs to update dynamically#}
    {% if answered_correctly %}
        <h4 align="center">You answered correctly :)</h4>
    {% else %}
        <h4 align="center">You answered incorrectly :(</h4>
    {% endif %}
    <br/>

    {{ table|safe }}
    <br/>
    <div style="text-align:center">
      <a href="{{ url_for('student.question') }}">Next Question</a>
    </div>

    <!--
    <br/>
        <div class="center" style="margin-bottom: 10px; border: 3px solid #555; width: 50%; text-align: center">
            <h4 style="margin: 20px;">{{ question }}</h4>
            <h4 style="margin: 20px;">{{ correct_answer }}</h4>
        </div>
    <br/>
    <h4>Score: 2/10</h4>
    -->
{% endblock %}

quiz_app/templates/student_landing.html
{% extends "base.html" %}
{% block content %}
    <br/>
    <img alt="Quizzly logo" class="center" src="{{ url_for('static', filename='images/quizzly logo.png')}}" width="80">
    <h2 style="margin: 2px" align="center">Please enter the Quiz ID and your username below</h2>
    <div class="container" align="center">
    <form method="POST">
        {{ form.hidden_tag() }}
        <div class="row" align="center" style="width: 40%">
        {{ form.name.label}}
        {{ form.name(autofocus=true)}}
        </div>
        <div class="row" align="center" style="width: 40%">
        {{ form.quiz_id.label}}
        {{ form.quiz_id()}}
        </div>
        <nav>
            <a href="{{ url_for('student.student_quiz_lobby') }}">
                {{ form.submit(class_="small-button-custom") }}
            </a>
        </nav>
    </form>
    {%  for mess  in get_flashed_messages() %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>Quiz ID not found!</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
    {{mess}}
    {%  endfor %}
    </div>

    </div>
{% endblock %}

quiz_app/templates/student_quiz_lobby.html
{% extends "base.html" %}
{% block content %}
    <br/>
    <h2 style="margin: 2px" align="center">Your Quiz will begin shortly</h2>
    <br/>
    <div style="position: absolute; left: 50%;">
        <img alt="Quizzly logo" class="center" src="{{ url_for('static', filename='images/quizzly logo.png')}}" width="80" style="position: relative; left: -50%;">
        <div class="loader" style="position: relative; left: -50%; margin-top: -93px"></div>
    </div>
    <br/><br/><br/><br/><br/><br/>
    <div class="container" align="center">
    <form method="POST">
        {{ form.hidden_tag() }}
        {{ form.start() }}
    </form>
    </div>
{% endblock %}

quiz_app/templates/teacher_landing.html
{% extends "base.html" %}
{% block content %}
    <br/>
    <img alt="Quizzly logo" class="center" src="{{ url_for('static', filename='images/quizzly logo.png')}}" width="80">
    <h2 style="margin: 2px" align="center">Please select a Quiz option below</h2>
    <br/>
    <div class="container" align="center">
    <div method="POST">
        {{ form.hidden_tag() }}
        <div class="row" align="center"">
            <div class="column" align="center">
                {{ form.existing(class_="other-button-custom")}}
            </div>
            <div class="column" align="center">
                {{ form.create(class_="other-button-custom")}}
            </div>
        </div>
    </div>
    </div>
{% endblock %}

quiz_app/templates/teacher_quiz_lobby.html
{% extends "base.html" %}
{% block content %}
    <br/>
    <h2 style="margin: 2px" align="center">Success! Your quiz ID is {{quiz_id}}.</h2>
    <br/>
    <div align="center">
    <img src="{{ qrcode_png_str }}"/>
    <br/><br/>
    <button>Start quiz</button>
    </div>
{% endblock %}